[tool.poetry]
name = "rbe511-swarm-intelligence"
version = "0.1.0"
description = "Homework assignments for RBE511 Swarm Intelligence"
authors = ["Nathaniel Bernal"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
numpy = "^2.4.6"
matplotlib = "^3.10.9"
scipy = "^1.17.1"


[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
